### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by davelab6** [quitequinn/TypeTester_TDF#1]
What license is this project available under? :)

**Comment by quitequinn** [comment]
Good call Dave, I'll speak with the folks at TDF and update appropriately.

**Comment by davelab6** [comment]
Probably Apache is best; MIT/BSD doesn't protect you from patent trolls

**Comment by quitequinn** [comment]
I suggested GPLv3. Considering TDF had to pay for it I imagine they don't want commercial products to freely use it. If they don't mind I'll use Apache.

**Comment by davelab6** [comment]
Even better!

**Comment by quitequinn** [comment]
Thanks for asking Dave. We have decided to keep the repo public but keep the licensing closed. I'm going to add a Copyright for clarity to the README now. If you need this repo shoot me a msg and we can talk more. Thanks for asking and I'm sorry we can't open source it. I've learned a valuable lesson about licensing today. Thanks!

**Comment by quitequinn** [comment]
Oh.. I guess it was always marked that way.
https://github.com/quitequinn/TypeTester_TDF/blob/master/LICENSE.html

**Comment by davelab6** [comment]
Sadly a lot of people don't understand that no license means no permission
to use it and will just do so, do i recommend removing the repo and just
having a homepage in this case :)

**Comment by HinTak** [comment]
Hmm, 'recommend removing the repo and just having a homepage' seems a bit inappropriate. A look-but-don't-use license is not a bad thing.

Some people have nice cars, they park in the street corner. On-lookers (or car designers, for that matter) enjoying looking at them, the owners like being admired. Parking in the street corner is not an invitation to a free ride. And that's fine. You cannot say: since you park your car in the street corner, you must like to give others free rides.

That's like asking owners of nice cars, if you don't want to give others free rides, you should lock your nice car in your own garage, away from the public eyes.

**Comment by davelab6** [comment]
The difference is that you can't be jailed for looking at the nice car but
you van be jailed for copyright infringement which is what downloading and
using the code in this repo is.

**Comment by HinTak** [comment]
I think the benefit of having (even copyrighted) code out there for downloading and private reference, is a good thing. Nobody in a clear head would deploy software own and developed by others without checking the license. You could get jailed for copyright infringement if you copy books from public libraries too. That does not say public libraries should not exist.

**Comment by davelab6** [comment]
Reading code you don't have a license to is a VERY BAD idea, because it
means that code you subsequently write can be considered a derivative work
and thus subject you to stiff penalties.

Whereas admiring a car is not taking action, copying a book borrowed from a
library is taking action that is above and beyond the normal purpose of
borrowed books, reading them. With code, running the code unlicensed is not
allowed, reading the code is dangerous.

There is no good reason to have unlicensed code published. It just presents
a hazard to the unwary.

**Comment by HinTak** [comment]
But that's the same argument about reading copyrighted books being dangerous - sadly - anything that comes out of your mouth, and any sentence you write, could be considered derivative work...

**Comment by quitequinn** [comment]
I'm with @HinTak on this one. If it wasn't for publicly readable copywrite work I wouldn't know half as much as I do. Which reminds me — big props to google fonts and @davelab6 (right?) for commissioning all those new families and releasing their ufos.

I don't want to accept a world were my trade can be considered a derivative and therefor not belong to me. Either way there is a license attached. I understand your concern @davelab6 but I think I'm going to leave the repo as is.

**Comment by davelab6** [comment]
Fair enough :) will you accept a PR to warn about this in the readme? :)

**Comment by quitequinn** [comment]
No need! I'll update it now.

**Comment by davelab6** [comment]
Ok great :) thanks for the kind words :)
